galaxy_url: "http://galaxy.uni-freiburg.de/"
api_key: "f963e720ce13fab7bf5291cb0b89be03"
library_names:
  input_data: "Prinz"
  genome_annotations: "Genomes + annotations"
folder_names:
  input_data: "derny/15-05-2017"
  annotation: "Annotations"
hist_name: "RNA seq analysis test"
annotation_name: "Mus_musculus.GRCm38.87.gtf (mm10)"
collection_names:
  raw_data: "Raw data"
  fastqc:
    web_report: "QC with FastQC: web report"
    raw_report: "QC with FastQC: raw report"
  trim_galore:
    report: "Trimming with Trim Galore!: report"
    trimmed: "Trimming with Trim Galore!: trimmed reads"
  preliminary_mapping:
    seq_extraction: "Preliminary mapping: downsampled reads"
    star:
      mapped: "Preliminary mapping: mapped reads"
      log: "Preliminary mapping: log"
      splice_junctions: "Preliminary mapping: splice junctions"
    infer_experiment: "Preliminary mapping: inferred experiments"
  star:
    mapped: "Mapping with STAR: mapped reads"
    log: "Mapping with STAR: log"
    splice_junctions: "Mapping with STAR: splice junctions"
name_prefix:
  raw_data: "Raw data for "
  fastqc: "FastQC for "
  trimgalore: "Trim Galore! for "
tool_names:
  merging: "Concatenate datasets"
  multiqc: "multiqc"
  fastqc: "FastQC"
  trim_galore: "Trim Galore!"
  seq_extraction: "Select first"
  star: "RNA STAR"
  infer_experiment: "Infer Experiment"
tool_versions:
  merging: "0.1.0"
  multiqc: "1.0.0.0"
  fastqc: "0.68"
  trim_galore: "0.4.3.0"
  seq_extraction: "1.1.0"
  star: "2.5.2b-0"
  infer_experiment: "2.4galaxy1"