galaxy_url: "http://galaxy.uni-freiburg.de/"
api_key: "f963e720ce13fab7bf5291cb0b89be03"
library_name: "Prinz"
folder_name: "derny/15-05-2017"
hist_name: "Neuromac GF RNA seq analysis"
collection_names:
  raw_data: "Raw data"
  fastqc: "FastQC"
  trimgalore: "Trim Galore!"
name_prefix:
  raw_data: "Raw data for "
  fastqc: "FastQC for "
  trimgalore: "Trim Galore! for "
tool_names:
  merging: "Concatenate datasets"
  multiqc: "multiqc"
  fastqc: "FastQC"
  trim_galore: "Trim Galore!"
tool_versions:
  merging: "0.1.0"
  multiqc: "1.0.0.0"
  fastqc: "0.68"
  trim_galore: "0.4.3.0"