galaxy_url: "http://galaxy.uni-freiburg.de/"
api_key: "f963e720ce13fab7bf5291cb0b89be03"
library_names:
  input_data: "Prinz"
  genome_annotations: "Genomes + annotations"
folder_names:
  input_data: "derny/15-05-2017"
  annotation: "Annotations/2017"
hist_name: "RNA seq analysis test"
annotation_name: "mm10_UCSC_07_15_genes.gtf"
collection_names:
  raw_data: "Raw data"
  fastqc:
    web_report: "QC with FastQC: web report"
    raw_report: "QC with FastQC: raw report"
  trim_galore:
    report: "Trimming with Trim Galore!: report"
    trimmed: "Trimming with Trim Galore!: trimmed reads"
  preliminary_mapping:
    seq_extraction: "Preliminary mapping: downsampled reads"
    star:
      mapped: "Preliminary mapping: mapped reads"
      log: "Preliminary mapping: log"
      splice_junctions: "Preliminary mapping: splice junctions"
    infer_experiment: "Preliminary mapping: inferred experiments"
  star:
    mapped: "Mapping with STAR: mapped reads"
    log: "Mapping with STAR: log"
    splice_junctions: "Mapping with STAR: splice junctions"
  feature_counts:
    counts: "Counting: count table"
    summary: "Counting: summary"
name_prefix:
  raw_data: "Raw data for "
  fastqc: "FastQC for "
  trimgalore: "Trim Galore! for "
tool_ids:
  merging: "toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_cat/0.1.0"
  multiqc: "toolshed.g2.bx.psu.edu/repos/engineson/multiqc/multiqc/1.0.0.0"
  fastqc: "toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.68"
  trim_galore: "toolshed.g2.bx.psu.edu/repos/bgruening/trim_galore/trim_galore/0.4.3.0"
  seq_extraction: "toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_head_tool/1.1.0"
  star: "toolshed.g2.bx.psu.edu/repos/iuc/rgrnastar/rna_star/2.5.2b-0"
  infer_experiment: "toolshed.g2.bx.psu.edu/repos/nilesh/rseqc/rseqc_infer_experiment/2.4galaxy1"
  feature_counts: "toolshed.g2.bx.psu.edu/repos/iuc/featurecounts/featurecounts/1.4.6.p5"
  deseq: "toolshed.g2.bx.psu.edu/repos/iuc/deseq2/deseq2/2.11.39"
  filter: "Filter1"
  cut: "toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_cut_tool/1.1.0"
  add_input_name_as_column: "toolshed.g2.bx.psu.edu/repos/mvdbeek/add_input_name_as_column/addName/0.1.1"
  convert: "Convert characters1"
  cat: "toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_cat/0.1.0"
  replace: "toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_replace_in_column/1.1.0"
  add_column: "toolshed.g2.bx.psu.edu/repos/devteam/column_maker/Add_a_column1/1.1.0"
  awk: "toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_awk_tool/1.1.0"