# Global metadata
title: The Gut Microbiome drives sex-biased microbial aging
description: >
  Differential gene expression analysis in mice for different microbiota, different ages and 2 sexes
# Social
email: berenice.batut@gmail.com
repository: bebatut/neuromac_GF_mices