library(DESeq2)
library(pheatmap)
library(gplots)
library(UpSetR)
library(ggplot2)
library(grid)
library(plyr)
require(graphics)
require(grDevices)
library(RColorBrewer)
library(viridis)
library(org.Mm.eg.db)
library(rentrez)
library(goseq)
library(dendextend)


library(WGCNA)
allowWGCNAThreads()
options(stringsAsFactors = FALSE)
library(igraph)
library(clusterProfiler)